version: "3.9"
services:
  db:
    image: mongo
    ports:
      - "27018:27017"
  nuxt:
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - "db"
    environment:
      - DB_URL=mongodb://db:27017/secret-db
